/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'microprocessor'
 * SOPC Builder design path: ../../microprocessor.sopcinfo
 *
 * Generated: Wed May 11 17:51:48 PDT 2016
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00002820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0xe
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0x00001020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0xe
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00001000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00002820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0xe
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0x00001020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0xe
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00001000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_NIOS2_GEN2


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x3110
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x3110
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x3110
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "microprocessor"


/*
 * bathArriving configuration
 *
 */

#define ALT_MODULE_CLASS_bathArriving altera_avalon_pio
#define BATHARRIVING_BASE 0x30a0
#define BATHARRIVING_BIT_CLEARING_EDGE_REGISTER 0
#define BATHARRIVING_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BATHARRIVING_CAPTURE 0
#define BATHARRIVING_DATA_WIDTH 1
#define BATHARRIVING_DO_TEST_BENCH_WIRING 0
#define BATHARRIVING_DRIVEN_SIM_VALUE 0
#define BATHARRIVING_EDGE_TYPE "NONE"
#define BATHARRIVING_FREQ 50000000
#define BATHARRIVING_HAS_IN 0
#define BATHARRIVING_HAS_OUT 1
#define BATHARRIVING_HAS_TRI 0
#define BATHARRIVING_IRQ -1
#define BATHARRIVING_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BATHARRIVING_IRQ_TYPE "NONE"
#define BATHARRIVING_NAME "/dev/bathArriving"
#define BATHARRIVING_RESET_VALUE 0
#define BATHARRIVING_SPAN 16
#define BATHARRIVING_TYPE "altera_avalon_pio"


/*
 * bathLeaving configuration
 *
 */

#define ALT_MODULE_CLASS_bathLeaving altera_avalon_pio
#define BATHLEAVING_BASE 0x30b0
#define BATHLEAVING_BIT_CLEARING_EDGE_REGISTER 0
#define BATHLEAVING_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BATHLEAVING_CAPTURE 0
#define BATHLEAVING_DATA_WIDTH 1
#define BATHLEAVING_DO_TEST_BENCH_WIRING 0
#define BATHLEAVING_DRIVEN_SIM_VALUE 0
#define BATHLEAVING_EDGE_TYPE "NONE"
#define BATHLEAVING_FREQ 50000000
#define BATHLEAVING_HAS_IN 0
#define BATHLEAVING_HAS_OUT 1
#define BATHLEAVING_HAS_TRI 0
#define BATHLEAVING_IRQ -1
#define BATHLEAVING_IRQ_INTERRUPT_CONTROLLER_ID -1
#define BATHLEAVING_IRQ_TYPE "NONE"
#define BATHLEAVING_NAME "/dev/bathLeaving"
#define BATHLEAVING_RESET_VALUE 0
#define BATHLEAVING_SPAN 16
#define BATHLEAVING_TYPE "altera_avalon_pio"


/*
 * chamberFull configuration
 *
 */

#define ALT_MODULE_CLASS_chamberFull altera_avalon_pio
#define CHAMBERFULL_BASE 0x3080
#define CHAMBERFULL_BIT_CLEARING_EDGE_REGISTER 0
#define CHAMBERFULL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CHAMBERFULL_CAPTURE 0
#define CHAMBERFULL_DATA_WIDTH 1
#define CHAMBERFULL_DO_TEST_BENCH_WIRING 0
#define CHAMBERFULL_DRIVEN_SIM_VALUE 0
#define CHAMBERFULL_EDGE_TYPE "NONE"
#define CHAMBERFULL_FREQ 50000000
#define CHAMBERFULL_HAS_IN 0
#define CHAMBERFULL_HAS_OUT 1
#define CHAMBERFULL_HAS_TRI 0
#define CHAMBERFULL_IRQ -1
#define CHAMBERFULL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CHAMBERFULL_IRQ_TYPE "NONE"
#define CHAMBERFULL_NAME "/dev/chamberFull"
#define CHAMBERFULL_RESET_VALUE 0
#define CHAMBERFULL_SPAN 16
#define CHAMBERFULL_TYPE "altera_avalon_pio"


/*
 * drain configuration
 *
 */

#define ALT_MODULE_CLASS_drain altera_avalon_pio
#define DRAIN_BASE 0x3050
#define DRAIN_BIT_CLEARING_EDGE_REGISTER 0
#define DRAIN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DRAIN_CAPTURE 0
#define DRAIN_DATA_WIDTH 1
#define DRAIN_DO_TEST_BENCH_WIRING 0
#define DRAIN_DRIVEN_SIM_VALUE 0
#define DRAIN_EDGE_TYPE "NONE"
#define DRAIN_FREQ 50000000
#define DRAIN_HAS_IN 0
#define DRAIN_HAS_OUT 1
#define DRAIN_HAS_TRI 0
#define DRAIN_IRQ -1
#define DRAIN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DRAIN_IRQ_TYPE "NONE"
#define DRAIN_NAME "/dev/drain"
#define DRAIN_RESET_VALUE 0
#define DRAIN_SPAN 16
#define DRAIN_TYPE "altera_avalon_pio"


/*
 * drainFinished configuration
 *
 */

#define ALT_MODULE_CLASS_drainFinished altera_avalon_pio
#define DRAINFINISHED_BASE 0x3020
#define DRAINFINISHED_BIT_CLEARING_EDGE_REGISTER 0
#define DRAINFINISHED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DRAINFINISHED_CAPTURE 0
#define DRAINFINISHED_DATA_WIDTH 1
#define DRAINFINISHED_DO_TEST_BENCH_WIRING 0
#define DRAINFINISHED_DRIVEN_SIM_VALUE 0
#define DRAINFINISHED_EDGE_TYPE "NONE"
#define DRAINFINISHED_FREQ 50000000
#define DRAINFINISHED_HAS_IN 0
#define DRAINFINISHED_HAS_OUT 1
#define DRAINFINISHED_HAS_TRI 0
#define DRAINFINISHED_IRQ -1
#define DRAINFINISHED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DRAINFINISHED_IRQ_TYPE "NONE"
#define DRAINFINISHED_NAME "/dev/drainFinished"
#define DRAINFINISHED_RESET_VALUE 0
#define DRAINFINISHED_SPAN 16
#define DRAINFINISHED_TYPE "altera_avalon_pio"


/*
 * fill configuration
 *
 */

#define ALT_MODULE_CLASS_fill altera_avalon_pio
#define FILL_BASE 0x3040
#define FILL_BIT_CLEARING_EDGE_REGISTER 0
#define FILL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FILL_CAPTURE 0
#define FILL_DATA_WIDTH 1
#define FILL_DO_TEST_BENCH_WIRING 0
#define FILL_DRIVEN_SIM_VALUE 0
#define FILL_EDGE_TYPE "NONE"
#define FILL_FREQ 50000000
#define FILL_HAS_IN 0
#define FILL_HAS_OUT 1
#define FILL_HAS_TRI 0
#define FILL_IRQ -1
#define FILL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FILL_IRQ_TYPE "NONE"
#define FILL_NAME "/dev/fill"
#define FILL_RESET_VALUE 0
#define FILL_SPAN 16
#define FILL_TYPE "altera_avalon_pio"


/*
 * fillFinished configuration
 *
 */

#define ALT_MODULE_CLASS_fillFinished altera_avalon_pio
#define FILLFINISHED_BASE 0x3030
#define FILLFINISHED_BIT_CLEARING_EDGE_REGISTER 0
#define FILLFINISHED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FILLFINISHED_CAPTURE 0
#define FILLFINISHED_DATA_WIDTH 1
#define FILLFINISHED_DO_TEST_BENCH_WIRING 0
#define FILLFINISHED_DRIVEN_SIM_VALUE 0
#define FILLFINISHED_EDGE_TYPE "NONE"
#define FILLFINISHED_FREQ 50000000
#define FILLFINISHED_HAS_IN 0
#define FILLFINISHED_HAS_OUT 1
#define FILLFINISHED_HAS_TRI 0
#define FILLFINISHED_IRQ -1
#define FILLFINISHED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FILLFINISHED_IRQ_TYPE "NONE"
#define FILLFINISHED_NAME "/dev/fillFinished"
#define FILLFINISHED_RESET_VALUE 0
#define FILLFINISHED_SPAN 16
#define FILLFINISHED_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 4
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * innerDoorOpen configuration
 *
 */

#define ALT_MODULE_CLASS_innerDoorOpen altera_avalon_pio
#define INNERDOOROPEN_BASE 0x3070
#define INNERDOOROPEN_BIT_CLEARING_EDGE_REGISTER 0
#define INNERDOOROPEN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define INNERDOOROPEN_CAPTURE 0
#define INNERDOOROPEN_DATA_WIDTH 1
#define INNERDOOROPEN_DO_TEST_BENCH_WIRING 0
#define INNERDOOROPEN_DRIVEN_SIM_VALUE 0
#define INNERDOOROPEN_EDGE_TYPE "NONE"
#define INNERDOOROPEN_FREQ 50000000
#define INNERDOOROPEN_HAS_IN 0
#define INNERDOOROPEN_HAS_OUT 1
#define INNERDOOROPEN_HAS_TRI 0
#define INNERDOOROPEN_IRQ -1
#define INNERDOOROPEN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define INNERDOOROPEN_IRQ_TYPE "NONE"
#define INNERDOOROPEN_NAME "/dev/innerDoorOpen"
#define INNERDOOROPEN_RESET_VALUE 0
#define INNERDOOROPEN_SPAN 16
#define INNERDOOROPEN_TYPE "altera_avalon_pio"


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x3110
#define JTAG_UART_IRQ 5
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x1000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "microprocessor_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 4096
#define ONCHIP_MEMORY_SPAN 4096
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * outerDoorOpen configuration
 *
 */

#define ALT_MODULE_CLASS_outerDoorOpen altera_avalon_pio
#define OUTERDOOROPEN_BASE 0x3060
#define OUTERDOOROPEN_BIT_CLEARING_EDGE_REGISTER 0
#define OUTERDOOROPEN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define OUTERDOOROPEN_CAPTURE 0
#define OUTERDOOROPEN_DATA_WIDTH 1
#define OUTERDOOROPEN_DO_TEST_BENCH_WIRING 0
#define OUTERDOOROPEN_DRIVEN_SIM_VALUE 0
#define OUTERDOOROPEN_EDGE_TYPE "NONE"
#define OUTERDOOROPEN_FREQ 50000000
#define OUTERDOOROPEN_HAS_IN 0
#define OUTERDOOROPEN_HAS_OUT 1
#define OUTERDOOROPEN_HAS_TRI 0
#define OUTERDOOROPEN_IRQ -1
#define OUTERDOOROPEN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define OUTERDOOROPEN_IRQ_TYPE "NONE"
#define OUTERDOOROPEN_NAME "/dev/outerDoorOpen"
#define OUTERDOOROPEN_RESET_VALUE 0
#define OUTERDOOROPEN_SPAN 16
#define OUTERDOOROPEN_TYPE "altera_avalon_pio"


/*
 * personInside configuration
 *
 */

#define ALT_MODULE_CLASS_personInside altera_avalon_pio
#define PERSONINSIDE_BASE 0x3090
#define PERSONINSIDE_BIT_CLEARING_EDGE_REGISTER 0
#define PERSONINSIDE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PERSONINSIDE_CAPTURE 0
#define PERSONINSIDE_DATA_WIDTH 1
#define PERSONINSIDE_DO_TEST_BENCH_WIRING 0
#define PERSONINSIDE_DRIVEN_SIM_VALUE 0
#define PERSONINSIDE_EDGE_TYPE "NONE"
#define PERSONINSIDE_FREQ 50000000
#define PERSONINSIDE_HAS_IN 0
#define PERSONINSIDE_HAS_OUT 1
#define PERSONINSIDE_HAS_TRI 0
#define PERSONINSIDE_IRQ -1
#define PERSONINSIDE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERSONINSIDE_IRQ_TYPE "NONE"
#define PERSONINSIDE_NAME "/dev/personInside"
#define PERSONINSIDE_RESET_VALUE 0
#define PERSONINSIDE_SPAN 16
#define PERSONINSIDE_TYPE "altera_avalon_pio"

#endif /* __SYSTEM_H_ */
